### ISSUE TITLE
Date-Time validation when syncing from tap

### ISSUE THREAD

**Issue by jimgibbs** [datamill-co/target-postgres#125]
I am attempting to leverage this target running it against my tap I get a ValidationError for my date-time 2018-12-03T16:59:03 in my schema I do specify this as a string with a format date-time... what do you believe I am missing?

Here is a sample of the output from the console:

```
INFO GET https://noho.api.rentmanager.com/Tenants?fields=FirstName,IsCompany,IsProspect,LastName,Name,PropertyID,RentDueDay,RentPeriod,Status,TenantID,UpdateDate&pagesize=100&pagenumber=1
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 8.24599003791809, "tags": {"http_status_code": 200, "status": "succeeded"}}
CRITICAL ('Invalid records detected above threshold: 0. See `.args` for details.', [(<ValidationError: "'2018-12-03T16:59:03' is not a 'date-time'">, {'type': 'RECORD', 'stream': 'tenants', 'record': {'TenantID': 554, 'Name': 'Michael Andrews', 'FirstName': 'Michael', 'LastName': 'Andrews', 'IsCompany': False, 'RentDueDay': 1, 'RentPeriod': 'Monthly', 'IsProspect': False, 'PropertyID': 90, 'UpdateDate': '2018-12-03T16:59:03', 'Status': 'Past'}})])
WARNING Invalid records detected for stream tenants: [(<ValidationError: "'2018-12-03T16:59:03' is not a 'date-time'">, {'type': 'RECORD', 'stream': 'tenants', 'record': {'TenantID': 554, 'Name': 'Michael Andrews', 'FirstName': 'Michael', 'LastName': 'Andrews', 'IsCompany': False, 'RentDueDay': 1, 'RentPeriod': 'Monthly', 'IsProspect': False, 'PropertyID': 90, 'UpdateDate': '2018-12-03T16:59:03', 'Status': 'Past'}})]
Traceback (most recent call last):
  File "c:\users\jim\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jim\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jim\AppData\Local\Programs\Python\Python37\Scripts\target-postgres.exe\__main__.py", line 9, in <module>
  File "c:\users\jim\appdata\local\programs\python\python37\lib\site-packages\target_postgres\__init__.py", line 36, in cli
    main(args.config)
  File "c:\users\jim\appdata\local\programs\python\python37\lib\site-packages\target_postgres\__init__.py", line 30, in main
    target_tools.main(postgres_target)
  File "c:\users\jim\appdata\local\programs\python\python37\lib\site-packages\target_postgres\target_tools.py", line 25, in main
    stream_to_target(input_stream, target, config=config)
  File "c:\users\jim\appdata\local\programs\python\python37\lib\site-packages\target_postgres\target_tools.py", line 69, in stream_to_target
    raise e
  File "c:\users\jim\appdata\local\programs\python\python37\lib\site-packages\target_postgres\target_tools.py", line 58, in stream_to_target
    line)
  File "c:\users\jim\appdata\local\programs\python\python37\lib\site-packages\target_postgres\target_tools.py", line 151, in _line_handler
    streams[line_data['stream']].add_record_message(line_data)
  File "c:\users\jim\appdata\local\programs\python\python37\lib\site-packages\target_postgres\singer_stream.py", line 156, in add_record_message
    self.invalid_records)
```

If you need an example of the schema file or anything else please let me know.

**Comment by AlexanderMann** [comment]
Hey @jimgibbs! So I punched the above into a test and was able to get it to validate correctly...I'm wondering if there's something funky with your config/schema...

If it's _not_ sensitive, can you upload the schema, any notable configuration, and then the command you're using to run this?

**Comment by jimgibbs** [comment]
This is the schema for the record shown in the log provided.

[tenants.zip](https://github.com/datamill-co/target-postgres/files/3310080/tenants.zip)

tap-rentmanager --config config.json | target-postgres --config postgres.json

Let me know if you need anything else.

**Comment by jimgibbs** [comment]
@AlexanderMann appears that the datetime coming from our system is incorrect OR there is a validation issue with the date-time parser.

**Comment by AlexanderMann** [comment]
@jimgibbs so I won't be able to look at this in depth till next week probably (family travel and the ever dreaded _worrrrrkkkkk_) but I'd recommend doing two things:

1. Look at our [Sandbox Tests](https://github.com/datamill-co/target-postgres/blob/master/tests/test_sandbox.py) for bonafide examples of `date-time`s which _do_ work
2. Also try pulling and running those tests locally, and modify some of the `date-time`s to _match_ yours

I'm curious if this _is_ a format thing, or whether we've somehow encountered a JSONSchema version and dependency management issue 😄

**Comment by AlexanderMann** [comment]
@jimgibbs did you have any luck tracking any of this down?

Last I checked my local tests seemed happy based on the input you provided. Happy to cook up a branch to try and reproduce etc.

If this is still an ongoing issue for you, then I'll make it a bug and try to track it down with more focus as this week I have set aside for open source maintenance etc.

**Comment by jimgibbs** [comment]
We put this portion of our project on hold. I do however think that some
timestamps do cause issues coming from "non-standard" JSON payloads. I
would not claim this is a high priority bug, but I do think it is worth
investigating at some point.

Thanks!

**Comment by AlexanderMann** [comment]
@jimgibbs can you give a look over this test here: https://github.com/datamill-co/target-postgres/pull/132

I wasn't able to reproduce this locally, but I'm hoping maybe CI will catch something? Or possibly I messed up something with the data you provided etc...
