### ISSUE TITLE
Unsupported type integer in existing target table - Trouble importing data from Stripe

### ISSUE THREAD

**Issue by tannerhallman** [datamill-co/target-postgres#166]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 242, in write_batch
    current_table_schema = self.get_table_schema(cur, root_table_name)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 778, in get_table_schema
    return self.__get_table_schema(cur, name)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 790, in __get_table_schema
    properties[column[0]] = self.sql_type_to_json_schema(column[1], column[2] == 'YES')
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 827, in sql_type_to_json_schema
    raise PostgresError('Unsupported type `{}` in existing target table'.format(sql_type))
target_postgres.exceptions.PostgresError: Unsupported type `integer` in existing target table
CRITICAL ('Exception writing records', PostgresError('Unsupported type `integer` in existing target table'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 242, in write_batch
    current_table_schema = self.get_table_schema(cur, root_table_name)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 778, in get_table_schema
    return self.__get_table_schema(cur, name)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 790, in __get_table_schema
    properties[column[0]] = self.sql_type_to_json_schema(column[1], column[2] == 'YES')
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 827, in sql_type_to_json_schema
    raise PostgresError('Unsupported type `{}` in existing target table'.format(sql_type))
target_postgres.exceptions.PostgresError: Unsupported type `integer` in existing target table

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/target-postgres", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/target_postgres/__init__.py", line 45, in cli
    main(args.config)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/__init__.py", line 39, in main
    target_tools.main(postgres_target)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/target_tools.py", line 27, in main
    stream_to_target(input_stream, target, config=config)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/target_tools.py", line 76, in stream_to_target
    raise e
  File "/usr/local/lib/python3.7/site-packages/target_postgres/target_tools.py", line 69, in stream_to_target
    state_tracker.flush_streams(force=True)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/stream_tracker.py", line 47, in flush_streams
    self._write_batch_and_update_watermarks(stream)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/stream_tracker.py", line 67, in _write_batch_and_update_watermarks
    self.target.write_batch(stream_buffer)
  File "/usr/local/lib/python3.7/site-packages/target_postgres/postgres.py", line 312, in write_batch
    raise PostgresError(message, ex)
target_postgres.exceptions.PostgresError: ('Exception writing records', PostgresError('Unsupported type `integer` in existing target table'))
```

**Comment by AlexanderMann** [comment]
@tannerhallman it looks like you might be trying to run `Target-Postgres` against a PostgreSQL schema which has some tables present in it which _**are not**_ managed by `Target-Postgres`? If that's the case, this is a known issue for usage and can often cause problems like the one documented above.

Given how `Target-Postgres` deals with denesting records and mapping table/column names, I'm unsure whether we'll take on trying to support it along side existing tables etc.

Can you detail more information about your given installation and usage?

**Comment by tannerhallman** [comment]
That's definitely the case. So it's recommended that I use a different, fresh (containing no preexisting tables) schema for using this target?

**Comment by AlexanderMann** [comment]
@tannerhallman yeah, if you can that's definitely a more easily supported approach. If you _cannot_ then I'd vote we move this issue from having a resolution of "Update the docs, provide better errors" to "Can't use this thing because of this use case" etc.

Thoughts?

**Comment by awm33** [comment]
Closing this since it seems to be a known feature limitation. Stitch (and maybe Fivetran?) also do not support writing to existing tables.
