### ISSUE TITLE
psycopg2.InternalError

### ISSUE THREAD

**Issue by owaismultani** [datamill-co/target-postgres#189]
Getting following error 
target:postgres

ERROR Exception writing records
Traceback (most recent call last):
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/postgres.py", line 234, in write_batch
    cur.execute('BEGIN;')
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/postgres.py", line 65, in execute
    return super(_MillisLoggingCursor, self).execute(query, vars)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/psycopg2/extras.py", line 461, in execute
    return super(LoggingCursor, self).execute(query, vars)
psycopg2.InternalError: there is already a transaction in progress

CRITICAL ('Exception writing records', InternalError('there is already a transaction in progress\n'))
Traceback (most recent call last):
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/postgres.py", line 234, in write_batch
    cur.execute('BEGIN;')
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/postgres.py", line 65, in execute
    return super(_MillisLoggingCursor, self).execute(query, vars)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/psycopg2/extras.py", line 461, in execute
    return super(LoggingCursor, self).execute(query, vars)
psycopg2.InternalError: there is already a transaction in progress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/__init__.py", line 39, in main
    target_tools.main(postgres_target)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/target_tools.py", line 28, in main
    stream_to_target(input_stream, target, config=config)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/target_tools.py", line 77, in stream_to_target
    raise e
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/target_tools.py", line 70, in stream_to_target
    state_tracker.flush_streams(force=True)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/stream_tracker.py", line 47, in flush_streams
    self._write_batch_and_update_watermarks(stream)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/stream_tracker.py", line 67, in _write_batch_and_update_watermarks
    self.target.write_batch(stream_buffer)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/postgres.py", line 309, in write_batch
    raise PostgresError(message, ex)
target_postgres.exceptions.PostgresError: ('Exception writing records', InternalError('there is already a transaction in progress\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/owais/anaconda3/envs/singer5/bin/target-postgres", line 8, in <module>
    sys.exit(cli())
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/__init__.py", line 45, in cli
    main(args.config)
  File "/home/owais/anaconda3/envs/singer5/lib/python3.8/site-packages/target_postgres/__init__.py", line 39, in main
    target_tools.main(postgres_target)
psycopg2.InternalError: there is no transaction in progress

**Comment by AlexanderMann** [comment]
@owaismultani can you please provide how you are running this, your local system, version of Python, version of Target Postgres, and whether the user you're using is connecting via anything else or if it is purely dedicated to this process?

**Comment by AlexanderMann** [comment]
Closing this due to inactivity and inability to reproduce. If this is a mistake, please comment/reopen!
