### ISSUE TITLE
KeyError attempting tap-csv to target-postgresql

### ISSUE THREAD

**Issue by EMCP** [datamill-co/target-postgres#206]
I am brand new to meltano and just following the instructions roughly speaking found here https://meltano.com/docs/getting-started.html#run-a-data-integration-el-pipeline

I configured everything (I think).. here's my `meltano.yml`

```
version: 1
send_anonymous_usage_stats: false
project_id: some_id
plugins:
  extractors:
  - name: tap-csv
    variant: meltano
    pip_url: git+https://gitlab.com/meltano/tap-csv.git
    config:
      files:
      - entity: example
        file: extract/example_data.csv
        keys:
        - col_name1
        - col_name2
        - col_name3
        - col_name4
        - col_name5
  loaders:
  - name: target-postgres
    variant: datamill-co
    pip_url: singer-target-postgres
    config:
      postgres_host: "some_non_local_ip"
      postgres_port: 5432
      postgres_username: my_user
      postgres_database: meltano
      postgres_schema: public
      disable_collection: true
```

but when i invoke I get something along the lines of `KeyError: 'col_name2'`

```
meltano elt tap-csv target-postgres --job_id=my-first-job 
meltano         | Running extract & load...
meltano         | No state was found, complete import.
meltano         | A catalog file was found, but it will be ignored as the extractor does not advertise the `catalog` or `properties` capability
tap-csv         | INFO Starting sync
tap-csv         | INFO Syncing entity 'col_name1' from file: 'extract/example_data.csv'
tap-csv         | INFO Sync completed
target-postgres | INFO PostgresTarget created with established connection: `user=some-user password=xxx dbname=meltano host=some_ip port=5432 sslmode=prefer sslcert=~/.postgresql/postgresql.crt sslkey=~/.postgresql/postgresql.key sslrootcert=~/.postgresql/root.crt sslcrl=~/.postgresql/root.crl`, PostgreSQL schema: `public`
target-postgres | INFO Stream col_name1 (col_name1) with max_version None targetting None
target-postgres | INFO Root table name col_name1
target-postgres | INFO Writing batch with 2 records for `col_name1` with `key_properties`: `['col_name1', 'col_name2', 'col_name3', 'col_name4', 'col_name5']`
target-postgres | INFO METRIC: {"type": "counter", "metric": "record_count", "value": 0, "tags": {"count_type": "batch_rows_persisted", "path": ["col_name1"], "database": "meltano", "schema": "public"}}
target-postgres | INFO METRIC: {"type": "timer", "metric": "job_duration", "value": 0.0007843971252441406, "tags": {"job_type": "batch", "path": ["col_name1"], "database": "meltano", "schema": "public", "status": "failed"}}
target-postgres | ERROR Exception writing records
target-postgres | Traceback (most recent call last):
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/postgres.py", line 295, in write_batch
target-postgres |     written_batches_details = self.write_batch_helper(cur,
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/sql_base.py", line 808, in write_batch_helper
target-postgres |     for table_batch in denest.to_table_batches(schema, key_properties, records):
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/denest.py", line 20, in to_table_batches
target-postgres |     table_schemas = _get_streamed_table_schemas(schema,
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/denest.py", line 47, in _get_streamed_table_schemas
target-postgres |     key_prop_schemas[key] = schema['properties'][key]
target-postgres | KeyError: 'col_name2'
target-postgres | CRITICAL ('Exception writing records', KeyError('col_name2'))
target-postgres | Traceback (most recent call last):
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/postgres.py", line 295, in write_batch
target-postgres |     written_batches_details = self.write_batch_helper(cur,
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/sql_base.py", line 808, in write_batch_helper
target-postgres |     for table_batch in denest.to_table_batches(schema, key_properties, records):
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/denest.py", line 20, in to_table_batches
target-postgres |     table_schemas = _get_streamed_table_schemas(schema,
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/denest.py", line 47, in _get_streamed_table_schemas
target-postgres |     key_prop_schemas[key] = schema['properties'][key]
target-postgres | KeyError: 'col_name2'
target-postgres | 
target-postgres | During handling of the above exception, another exception occurred:
target-postgres | 
target-postgres | Traceback (most recent call last):
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>
target-postgres |     sys.exit(cli())
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/__init__.py", line 45, in cli
target-postgres |     main(args.config)
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/__init__.py", line 39, in main
target-postgres |     target_tools.main(postgres_target)
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target_tools.py", line 28, in main
target-postgres |     stream_to_target(input_stream, target, config=config)
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target_tools.py", line 77, in stream_to_target
target-postgres |     raise e
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target_tools.py", line 70, in stream_to_target
target-postgres |     state_tracker.flush_streams(force=True)
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/stream_tracker.py", line 47, in flush_streams
target-postgres |     self._write_batch_and_update_watermarks(stream)
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/stream_tracker.py", line 67, in _write_batch_and_update_watermarks
target-postgres |     self.target.write_batch(stream_buffer)
target-postgres |   File "/home/Dev/git/meltano/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/postgres.py", line 309, in write_batch
target-postgres |     raise PostgresError(message, ex)
target-postgres | target_postgres.exceptions.PostgresError: ('Exception writing records', KeyError('col_name2'))
meltano         | Loading failed (1): target_postgres.exceptions.PostgresError: ('Exception writing records', KeyError('col_name2'))
meltano         | ELT could not be completed: Loader failed
ELT could not be completed: Loader failed
```

**Comment by EMCP** [comment]
my general question is.. should I already have in place.. the columns on the DB to recieve the data?  I am reading the instructions and it seems if I need to I can inject that here in the config

```
before_run_sql
```

"Raw SQL statement(s) to execute as soon as the connection to Postgres is opened by the target. Useful for setup like SET ROLE or other connection state that is important."
