### ISSUE TITLE
crashing when in use 

### ISSUE THREAD

**Issue by EMCP** [datamill-co/target-postgres#208]
I tried multiple times to execute this target with a tap..  unsure what is going on but thinking either I need to switch away from this target or break up my query so it's not as large

```
target-postgres | CRITICAL cursor already closed
target-postgres | Traceback (most recent call last):
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/postgres.py", line 234, in write_batch
target-postgres |     cur.execute('BEGIN;')
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/postgres.py", line 65, in execute
target-postgres |     return super(_MillisLoggingCursor, self).execute(query, vars)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/psycopg2/extras.py", line 461, in execute
target-postgres |     return super(LoggingCursor, self).execute(query, vars)
target-postgres | psycopg2.errors.AdminShutdown: terminating connection due to administrator command
target-postgres | server closed the connection unexpectedly
target-postgres | 	This probably means the server terminated abnormally
target-postgres | 	before or while processing the request.
target-postgres | 
target-postgres | 
target-postgres | During handling of the above exception, another exception occurred:
target-postgres | 
target-postgres | Traceback (most recent call last):
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/__init__.py", line 39, in main
target-postgres |     target_tools.main(postgres_target)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target_tools.py", line 28, in main
target-postgres |     stream_to_target(input_stream, target, config=config)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target_tools.py", line 77, in stream_to_target
target-postgres |     raise e
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/target_tools.py", line 70, in stream_to_target
target-postgres |     state_tracker.flush_streams(force=True)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/stream_tracker.py", line 47, in flush_streams
target-postgres |     self._write_batch_and_update_watermarks(stream)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/stream_tracker.py", line 67, in _write_batch_and_update_watermarks
target-postgres |     self.target.write_batch(stream_buffer)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/postgres.py", line 306, in write_batch
target-postgres |     cur.execute('ROLLBACK;')
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/postgres.py", line 65, in execute
target-postgres |     return super(_MillisLoggingCursor, self).execute(query, vars)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/psycopg2/extras.py", line 461, in execute
target-postgres |     return super(LoggingCursor, self).execute(query, vars)
target-postgres | psycopg2.InterfaceError: cursor already closed
target-postgres | 
target-postgres | During handling of the above exception, another exception occurred:
target-postgres | 
target-postgres | Traceback (most recent call last):
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/bin/target-postgres", line 8, in <module>
target-postgres |     sys.exit(cli())
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/__init__.py", line 45, in cli
target-postgres |     main(args.config)
target-postgres |   File "/home/ubuntu/meltano_proj_repo/.meltano/loaders/target-postgres/venv/lib/python3.8/site-packages/target_postgres/__init__.py", line 39, in main
target-postgres |     target_tools.main(postgres_target)
target-postgres | psycopg2.InterfaceError: connection already closed
```

**Comment by EMCP** [comment]
it works normally but only for smaller sets of queries

**Comment by gustavohwulee** [comment]
I've made a quick fix on the fork I'm using for some personal projects:
https://github.com/gustavohwulee/target-postgres/pull/1/files

**Comment by ericboucher** [comment]
Is this still an issue?

If so, @gustavohwulee would you like to propose your fix as a PR to this repo?

**Comment by ohld** [comment]
When the tap loads data for several minutes, target-postgres produces the error:
```
CRITICAL cursor already closed
Traceback (most recent call last):
  File "/Users//.pyenv/versions/3.10.0/lib/python3.10/site-packages/target_postgres/postgres.py", line 234, in write_batch
    cur.execute('BEGIN;')
  File "/Users//.pyenv/versions/3.10.0/lib/python3.10/site-packages/target_postgres/postgres.py", line 65, in execute
    return super(_MillisLoggingCursor, self).execute(query, vars)
  File "/Users//.pyenv/versions/3.10.0/lib/python3.10/site-packages/psycopg2/extras.py", line 461, in execute
    return super(LoggingCursor, self).execute(query, vars)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected
```

**Comment by EMCP** [comment]
@ohld I honestly recommend you switch off this variant .. if you're using meltano .. I no longer do postgresql but had better luck with the transferwise variant
